// client/src/components/footer.jsx
import './components-styles/footer.css';
import {ImGithub} from "react-icons/im";

export default function Footer() {
    return (
        <div className="footer">
            <footer className="footer_content">
                <br/>
                {/*Copyright text on bottom left*/}
                <a href="https://github.com/mtautonico/SwitchCompare/blob/main/LICENSE.md" target="_blank"
                   rel="noreferrer">
                    <span className="copyright footerlink">&copy; {new Date().getFullYear()} Michael Tautonico</span>
                </a>

                {/* GitHub Repo Link */}
                <a className="footerLink" href="https://github.com/mtautonico/SwitchCompare" target="_blank"
                   rel="noreferrer">
                    <div className="github">
                        <ImGithub size={25}/>
                    </div>
                </a>
            </footer>
        </div>
    )
}

// client/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import {faGithub} from "@fortawesome/free-brands-svg-icons";
import {faCoffee} from "@fortawesome/free-solid-svg-icons";

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.less']
})
export class FooterComponent {

  faGithub = faGithub;
  faCoffee = faCoffee;
  Year() {
    return new Date().getFullYear();
  }
}

<div class="footer-container">
  <div class="footer-content">
    <a href="https://github.com/mtautonico/SwitchCompare/blob/main/LICENSE.md" target="_blank"
       rel="noreferrer">
      <div class="copyrightContainer">
        <span class="copyright footerlink">&copy; {{Year()}} Michael Tautonico</span>
      </div>
    </a>
    <!--TODO: Add ko-fi link-->
    <div class="footerLinks">
      <a class="footerLink kofi" href="" target="_blank" rel="noreferrer">
        <fa-icon [icon]="faCoffee" size="3x"></fa-icon>
      </a>

      <!--GitHub Repo Link-->
      <a class="footerLink github" href="https://github.com/mtautonico/SwitchCompare" target="_blank"
         rel="noreferrer">
        <fa-icon [icon]="faGithub" size="3x"></fa-icon>
      </a>
    </div>
  </div>
</div>
